apiVersion: v1
kind: Namespace
metadata:
  name: ewf-space
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ewf-web-app
  namespace: ewf-space
  labels:
    app: ewf-web-app
spec:
  selector:
    matchLabels:
      app: ewf-web-app
  replicas: 3
  template:
    metadata:
      labels:
        app: ewf-web-app
    spec:
      containers:
      - name: web-app
        image: nexus-aws.dhl-ewf.kyiv.epam.com:5000/hackathon/webapp:v2.0
        imagePullPolicy: IfNotPresent
        env:
          - name: LISTENING_PORT
            value: "8080"
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /live
            port: "http"
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /ready
            port: "http"
            scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: ewf-web-app
  namespace: ewf-space
  labels:
    app: ewf-web-app
spec:
  type: NodePort
  selector:
    app: ewf-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
