apiVersion: v1
kind: Service
metadata:
  name: ewf-web-app
  labels:
    app: ewf-web-app
spec:
  type: NodePort
  selector:
    app: ewf-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
